# Generated by Django 3.1 on 2020-08-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200824_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='densitylevel',
            name='levelStr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='densitylevel',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
